name: django cicd pipeline

on:
    push: 
        branches:
            - master

jobs: 
    build-test :
        runs-on: ubuntu-latest
    
        steps: 
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: Setup Python
              uses: actions/setup-python@v5
            #   with:
            #     python-version: '3.11'

            - name: Install Dependecies
              run: |
                pip install django
            
            - name: Run Tests
              run: |
                python myproject/manage.py test
            
            - name: Deploy
              run: |
                echo "Deploying ..... "








